// <auto-generated />
namespace CustomerManagementSystem.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserTypeAdde3deed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTypeAdde3deed));
        
        string IMigrationMetadata.Id
        {
            get { return "201806172053520_UserTypeAdde3deed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
